### Create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "ahmadtesting",
    "author": "Fzzzzz",
    "desc": " the American Dream and the corruption of the 1920s.",
    "price": 10.99
}

### Get all books
GET http://localhost:3000/books


### Create a new member
POST http://localhost:3000/members
Content-Type: application/json

{
    "name": "ahmad saad",
    "email": "ahmad.saad@example.com",
    "phone": "+33333"
}


### get all members
GET http://localhost:3000/members


### get member by id
GET http://localhost:3000/members/2

### update member
PUT http://localhost:3000/members/1
Content-Type: application/json

{
    "name": "abdulmalik",
    "email": "abdlmalik@gmail.com",
    "phone": "+2222222"
}

### create a new loan
POST http://localhost:3000/loans
Content-Type: application/json

{
    "bookId": 2,
    "memberId": 1
}

### get all loans
GET http://localhost:3000/loans


### return a book
POST http://localhost:3000/returns
Content-Type: application/json

{
    "bookId": 2,
    "memberId": 1
}